### ISSUE TITLE
Apache 2.4 mod_proxy_fcgi and mod_rpaf doesn't forward translated REMOTE_ADDR to FPMs

### ISSUE THREAD

**Issue by motienko** [gnif/mod_rpaf#33]
We got configs (frontend revers proxy (mostly nginx or haproxy) + apache2.4 +mod_rpaf + php-fpm 5.5) like:

<VirtualHost *:80>
    DocumentRoot /www/sitename.ru
    ServerName sitename.ru
    ServerAlias www.sitename.ru
    RequestHeader set X-RESELLER "24224234"
    RequestHeader set X-SITE-FOLDER "sitename.ru"
    CustomLog /var/log/apache/sitename.ru_access_log combined
    ErrorLog /var/log/apache/sitename.ru_error_log

```
ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9061/www/sitename.ru/$1

<Directory /www/sitename.ru>
    Options -Indexes
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```

</VirtualHost>

The php-fpm config is default, except listen port.

We see proper/traslated IP address in apache logs, but php $_SERVER[REMOTE_ADDR] is address of reverse proxy host (our lan ip from 10._._.*) . 

Please help to resolve this problem.

**Comment by gnif** [comment]
1) Please format your questions properly, this is hard to read due to poor formatting.
2) Please post your mod_rpaf version
3) Please post your mod_rpaf configuration

Without providing proper information there is no way anyone can assist you.

**Comment by glensc** [comment]
@motienko you still lack mod_rpaf configuration.

**Comment by Hufschmidt** [comment]
I'll add some additional information to this, since I'm having the same issue. I'll post the relevent configurations and setup below:

## Loadbalancer

Running Nginx (1.8.1), delivers static content and proxies other requests to our internal workers...

### sites-enabled/proxy.conf

```
server {
  ...

  try_files $uri $uri/ @try_upstream;

  location @try_upstream {
    proxy_pass            http://worker;
    proxy_redirect        off;
    proxy_set_header      Host $host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;

    ...
  }
}
```

### conf.d/workers.conf

```
upstream worker {  
  server     192.168.1.1:80  fail_timeout=10s;
  server     192.168.1.2:80  fail_timeout=10s;
  server     192.168.1.3:80  fail_timeout=10s;
}
```

## Workers

Running Apache 2.4.10 + mod_proxy + mod_proxy_fcgi + php5-fpm 5.6.17, executes all php code...

### sites-enabled/upstream.conf

```
<VirtualHost 192.168.1.x:80>
  ...

  <Directory "/var/www">
    Options -Indexes +FollowSymLinks +MultiViews
    AllowOverride None
    Require all granted

    <FilesMatch ".+(\.php|\.php5|\.phtml)$">
        SetHandler 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost:9000/'
    </FilesMatch>
  </Directory>
</VirtualHost>
```

### mods-enabled/rpaf.conf

```
RPAFenable On
RPAFsetHostName On
RPAFproxy_IPs 137.248.1.19
RPAFheader X-Real-IP
```

**OR**

```
RPAFenable On
RPAFsetHostName On
RPAFproxy_IPs 137.248.1.19
RPAFheader X-Forward-For
```

### Misc
- OS on all systems is Debian 8 (Jessie)
- Apache, mod_rpaf, mod_proxy and mod_proxy_fcgi all from standard debian apt-get sources

### Descriptions

What is working? On the PHP side contains $_SERVER correct (actual client) values in keys HTTP_X_REAL_IP and HTTP_X_FORWARD_FOR, so nginx setup is working and correct.
In addition the apache access-log does also output the correct actual client ip, so my rpaf configuration is also correct. I verified this by disabling rpaf temporary, after which the loadbalancer ip is logged in the apache access-log.

PUT the problem is that $_SERVER['REMOTE_ADDR'] still contains the load-balancers ip address, even when the access-log is now correct.

### Fix?

I disabled mod_rpaf and activated mod_remoteip with the following added to my vhost config:

```
  RemoteIPHeader X-Forwarded-For
  RemoteIPInternalProxy 111.111.111.111
```

(_Where 111.111.111.111 would be my loadbalancers ip_)

This leaves me with the conclusion, that there is a problem with mod_rpaf. **My guess is it has something to do with using mod_proxy + mod_proxy_fcgi** (instead of the outdated mod_fcgi)...

**Comment by althaus** [comment]
I've just upgraded my server to Debian Jessie and have the same issue. `$_SERVER['REMOTE_ADDR']` isn't populated with the forwarded IP with a simple nginx-apache-setup. The same setup was working on Wheezy.

https://packages.debian.org/jessie/libapache2-mod-rpaf

**Comment by shaneshort** [comment]
I appear to be seeing this with Apache 2.4 on ubuntu xenial too.. It appears that x-forwarded-proto/SSL isn't being set, either.

**Comment by glensc** [comment]
I'm locked to old version (prior this github code) due this bug. I do not wish to modify all current and future configuration based whether mod_rpaf being enabled module or not.

**Comment by jpptinsley** [comment]
mod_rpaf appears to have been depreciated in Debian Jessie, and further development halted. Switch to mod_remoteip, which is a default module in Debian Jessie.

**Comment by gnif** [comment]
@jpptinsley: mod_rapf has NOT been deprecated and development has NOT been halted, mod_remoteip does not handle HTTPS forwarding and is rather feature lacking.

The issues here have all been fixed and resolved in mod_rpaf 0.7, all reported issues here are due to people using 0.6.

**Comment by glensc** [comment]
sadly #27 still present with 0.8 version

however, as mod_remoteip behaves same as mod_rpaf 0.8 from #27 i'm starting to believe it's [supposed to be](https://github.com/gnif/mod_rpaf/issues/27#issuecomment-158942296) that way in apache 2.4

**Comment by glensc** [comment]
@gnif care to comment my last note?

**Comment by sindarina** [comment]
For anyone who is finding this now, running into the same problem, note that the version present in the currently supported versions of Debian and Ubuntu is 0.6, even in Ubuntu Bionic and Debian Stretch, which means that this module is effectively abandoned, since later versions have not made it into either of these distros in the last two years.

The 'remoteip' module does indeed work, and is part of the default Apache package.

**Comment by gnif** [comment]
This module was never abandoned, the package maintainer simply never bothered to update to the latest version.

The simple fact of the matter is that all hosting services I operate no longer use Apache as such I no longer have a monetary reason to work on this project. If people are willing to fund development on this project I would be happy to continue to put effort into it. By no means is this abandoned, there just little motivation to put time into a project that no longer realizes any commercial value at this time.

**Comment by AndreiG6** [comment]
Funds were previously suggested to no avail in https://github.com/gnif/mod_rpaf/issues/42#issuecomment-269600292

It certainly seems *abandoned*!

**Comment by RomkaLTU** [comment]
rpaf not working anymore, at least that one whose ships with distro (Ubuntu Bionic).
So I just enabled mod_remoteip ant added **RemoteIPHeader X-Forwarded-For** in apache configuration.

I use Nginx as frontend, of course you must **set proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;** in nginx virtual hsot config.

**Comment by vlad88sv** [comment]
This still an issue in Ubuntu 20.04

`sudo a2enmod remoteip` and adding this to the VHost works wonders:

```
        RemoteIPHeader X-Forwarded-For
        RemoteIPInternalProxy 127.0.0.1
```

Thank you for the tip @RomkaLTU and @Hufschmidt
